"""Canonical DDG workbook tab names."""
from __future__ import annotations

TAB_EXEC_SUMMARY = "Executive Summary"
TAB_METHODOLOGY = "TAM Methodology"
TAB_CLASSIFICATION_METHOD = "Classification Method"
TAB_ASSUMPTIONS = "Assumptions"
TAB_DDG_TAM = "DDG-51 TAM"
TAB_SCN_BUDGET = "SCN Budget"
TAB_POP = "Place of Performance"
TAB_OBBBA = "OBBBA Mandatory"
TAB_FYDP = "FYDP Outyears"
TAB_DEFLATORS = "Deflators"
TAB_CHECKS = "Checks"

TAB_TAXONOMY = "Taxonomy"
TAB_NAICS_MAP = "Mapping - NAICS Defaults"
TAB_SWBS_CROSSWALK = "Mapping - HII Code to SWBS"
TAB_DDG_PROGRAM = "DDG Program Vendors"
TAB_SWBS_ROLLUP = "DDG SWBS by Ship-System"
TAB_DOMAIN_CONC = "Domain Concentration"
TAB_WHERE_TO_PLAY = "Where to Play"
TAB_MARKET_BRIDGE = "Market Bridge"
TAB_SUBAWARD_ACTIVITY = "Subaward Activity"
TAB_DDG_TX = "DDG Subaward Transactions"
TAB_PRIME_AWARDS = "Prime Awards"
TAB_SUPPLIER_MASTER = "Supplier Master"
TAB_SUPPLIER_YEAR = "Supplier-Year Activity"
TAB_ARCHETYPE_OVERRIDES = "Mapping - Vendor Overrides"
TAB_PIID_HULL_MAP = "Mapping - PIID to Hull"
TAB_HULL_MASTER = "DDG Hull Master"
TAB_HULL_SPEND = "DDG Hull Spend Summary"
TAB_HULL_COVERAGE = "DDG Hull Coverage"
TAB_HULL_SWBS = "DDG Hull x SWBS"
TAB_VENDOR_HULL = "DDG Vendor x Hull Exposure"
TAB_VENDOR_HULL_SWBS = "DDG Vendor x Hull x SWBS"
TAB_HULL_EXCEPTIONS = "DDG Hull Exceptions"
TAB_HULL_METHODOLOGY = "Hull Mapping Methodology"
TAB_HULL_LIFECYCLE = "DDG Hull x Lifecycle Stage"
TAB_CD_LC_COVERAGE = "DDG C-D Lifecycle Coverage"
TAB_CD_LC_ROLLUP = "DDG C-D Lifecycle Rollup"
TAB_CD_LC_CANDIDATES = "DDG C-D Lifecycle Candidates"
TAB_LIFECYCLE_METHOD = "Lifecycle Methodology"

assert all(len(n) <= 31 for n in globals().values() if isinstance(n, str))
