"""ddg_vendor_hull - DDG Vendor x Hull Exposure (one row per vendor x assigned hull).

The long-format vendor-to-hull view: which suppliers show up on which hulls, with their predominant
ship-system, lifetime assigned $, record count, and first/last action date. The row spine (distinct
UEI x Assigned Hull pairs, plus the static vendor name / builder / predominant SWBS / confidence) is
generated by scripts/build_ddg_vendor_hull.py; the dollar / record / date columns are live
two-criteria SUMIFS / COUNTIFS / MINIFS / MAXIFS over the DDG Subaward Transactions leaf, keyed on
this row's Subawardee UEI AND Assigned Hull. Only exact-hull (grade A/B) rows enter the spine, so a
conflict / family-only row never appears here.

(The lifecycle-keyed vendor-hull timeline - vendor activity by hull lifecycle stage - is a deferred
later phase that needs per-hull milestone dates.)
"""
from __future__ import annotations

from workbook_award_classification_refactor.sheets._flat import (
    make_flat_sheet, flat_header_letters,
)
from workbook_award_classification_refactor.sheets._fiscal import TX_REAL
from workbook_award_classification_refactor.sheets._tabs import TAB_VENDOR_HULL
from workbook_award_classification_refactor.sheets.ddg_subaward_transactions import (
    ddg_tx_cols,
)
from workbook_award_classification_refactor.sheets._widths import (
    W_UEI, W_SHORT_FLAG, W_VENDOR, W_SUPTYPE, W_CATEGORY, W_DOLLAR, W_COUNT, W_DATE, W_CODE,
)

# UEI | Hull | Vendor | Builder | Predominant SWBS | $M | Records | First | Last | Confidence
_WIDTHS = [W_UEI, W_SHORT_FLAG, W_VENDOR, W_SUPTYPE, W_CATEGORY,
           W_DOLLAR, W_COUNT, W_DATE, W_DATE, W_CODE]

# This sheet's own key column letters (gutter at A; no note source, no extra cols).
_L = flat_header_letters("ddg_vendor_hull_exposure")
_UEI_COL, _HULL_COL = _L["Subawardee UEI"], _L["Hull"]

# tx-leaf ranges the per-row measures aggregate over.
_UEI = ddg_tx_cols("Subawardee UEI")
_AHULL = ddg_tx_cols("Assigned Hull")
_DATE = ddg_tx_cols("Subaward Date")
_REAL = ddg_tx_cols(TX_REAL)


def _crit(r):
    return f"{_UEI},${_UEI_COL}{r},{_AHULL},${_HULL_COL}{r}"


_FORMULAS = {
    "Assigned $M":    lambda r: f"=SUMIFS({_REAL},{_crit(r)})/1000000",
    "Records":        lambda r: f"=COUNTIFS({_crit(r)})",
    "First Subaward": lambda r: f"=_xlfn.MINIFS({_DATE},{_crit(r)})",
    "Last Subaward":  lambda r: f"=_xlfn.MAXIFS({_DATE},{_crit(r)})",
}

DDG_VENDOR_HULL, vendor_hull_cols = make_flat_sheet(
    tab=TAB_VENDOR_HULL, group="model",
    csv_name="ddg_vendor_hull_exposure", table_name="DdgVendorHull",
    banner="§1 - DDG-51 vendor x hull exposure",
    intro="One row per supplier x assigned hull; assigned subawards in constant FY2026$.",
    widths=_WIDTHS,
    int_cols=["Records"], float_cols=["Assigned $M"],
    date_cols=["First Subaward", "Last Subaward"], formula_cols=_FORMULAS,
    input_cols=["Subawardee UEI"],
    # COUNTIFS / MINIFS / MAXIFS surface tx-sheet values -> green links; $M (a new SUMIFS) stays black.
    link_cols=["Records", "First Subaward", "Last Subaward"],
    display_headers={
        "Subawardee Vendor Name": "Vendor", "Predominant SWBS": "Top SWBS group",
    },
)
