"""ddg_vendor_hull_swbs - DDG Vendor x Hull x SWBS (one row per vendor x assigned hull x subsystem).

The finest vendor-to-hull view: which suppliers do which ship-system work on which hull. It refines
DDG Vendor x Hull Exposure (which collapses a vendor's work to one predominant SWBS group) down to
the SWBS subsystem grain. HII-Ingalls only - GD-BIW subawards carry no SWBS classification. The spine
(distinct UEI x Assigned Hull x SWBS subsystem, with static vendor / builder / SWBS labels /
confidence) is generated by scripts/build_ddg_vendor_hull.py; the dollar / record / date columns are
live THREE-criteria SUMIFS / COUNTIFS / MINIFS / MAXIFS over the DDG Subaward Transactions leaf, keyed
on this row's Subawardee UEI AND Assigned Hull AND SWBS Subsystem (the latter two are live formula
columns on that sheet, so this view tracks edits to the curated PIID->Hull map).
"""
from __future__ import annotations

from workbook_award_classification_refactor.sheets._flat import (
    make_flat_sheet, flat_header_letters,
)
from workbook_award_classification_refactor.sheets._fiscal import TX_REAL
from workbook_award_classification_refactor.sheets._tabs import TAB_VENDOR_HULL_SWBS
from workbook_award_classification_refactor.sheets.ddg_subaward_transactions import (
    ddg_tx_cols,
)
from workbook_award_classification_refactor.sheets._widths import (
    W_UEI, W_SHORT_FLAG, W_VENDOR, W_SUPTYPE, W_CATEGORY, W_CODE, W_TEXT,
    W_DOLLAR, W_COUNT, W_DATE,
)

# UEI | Hull | Vendor | Builder | SWBS major | subsystem | subsystem name |
#   $M | Records | First | Last | Confidence
_WIDTHS = [W_UEI, W_SHORT_FLAG, W_VENDOR, W_SUPTYPE, W_CATEGORY, W_CODE, W_TEXT,
           W_DOLLAR, W_COUNT, W_DATE, W_DATE, W_CODE]

# This sheet's own key column letters (gutter at A; no note source, no extra cols).
_L = flat_header_letters("ddg_vendor_hull_swbs")
_UEI_COL, _HULL_COL, _SUB_COL = _L["Subawardee UEI"], _L["Hull"], _L["SWBS Subsystem"]

# tx-leaf ranges the per-row measures aggregate over.
_UEI = ddg_tx_cols("Subawardee UEI")
_AHULL = ddg_tx_cols("Assigned Hull")
_SUBSYS = ddg_tx_cols("SWBS Subsystem")
_DATE = ddg_tx_cols("Subaward Date")
_REAL = ddg_tx_cols(TX_REAL)


def _crit(r):
    return (f"{_UEI},${_UEI_COL}{r},{_AHULL},${_HULL_COL}{r},"
            f"{_SUBSYS},${_SUB_COL}{r}")


_FORMULAS = {
    "Assigned $M":    lambda r: f"=SUMIFS({_REAL},{_crit(r)})/1000000",
    "Records":        lambda r: f"=COUNTIFS({_crit(r)})",
    "First Subaward": lambda r: f"=_xlfn.MINIFS({_DATE},{_crit(r)})",
    "Last Subaward":  lambda r: f"=_xlfn.MAXIFS({_DATE},{_crit(r)})",
}

DDG_VENDOR_HULL_SWBS, vendor_hull_swbs_cols = make_flat_sheet(
    tab=TAB_VENDOR_HULL_SWBS, group="model",
    csv_name="ddg_vendor_hull_swbs", table_name="DdgVendorHullSwbs",
    banner="§1 - DDG-51 vendor x hull x ship-system",
    intro="HII-Ingalls supplier x assigned hull x SWBS subsystem; assigned subawards in FY2026$.",
    widths=_WIDTHS,
    int_cols=["Records"], float_cols=["Assigned $M"],
    date_cols=["First Subaward", "Last Subaward"], formula_cols=_FORMULAS,
    input_cols=["Subawardee UEI"],
    link_cols=["Records", "First Subaward", "Last Subaward"],
    display_headers={
        "Subawardee Vendor Name": "Vendor", "SWBS Major Group": "SWBS group",
        "SWBS Subsystem Name": "Subsystem",
    },
)
